sudo: false
language: python

os:
  - linux

python:
  - "3.6"

global:
  env:
    - COMMIT_AUTHOR_EMAIL: "f.zapata@esciencecenter.nl"

install:
  # install library
  - pip install codecov
  - pip install -e .

script:
  - coverage run tests

branches:
  only:
    - master

after_success:
  - codecov